// Copyright (c) 2026 Jennifer Lewis. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
// See LICENSE file in the project root for full license text.

//======================================================================================================
// [HMAC-SHA256 + SHA-256 file digest — in-process, no shell-out]
//======================================================================================================
// Shared primitive for any code that needs HMAC-SHA256 or SHA-256 of a
// file. Uses openssl EVP — same library Binance signing already pulls in,
// so no new build dependency.
//
// Replaces two earlier shell-out paths (v5.2.0 Phase 1 hacks):
//   - ML_Headers/ModelInference.hpp `verify_model_stamp` invoked
//     `openssl dgst -sha256 -hmac '<secret>'` via popen.
//   - ML_Headers/ModelInference.hpp `sha256_file_hex` invoked
//     `sha256sum` via popen.
//
// In-process is faster, avoids shell-injection surface, and removes the
// dependency on /usr/bin/sha256sum + /usr/bin/openssl being on PATH.
//
// HMAC primitive matches what `tools/stamp_model.sh` uses (openssl dgst
// -sha256 -hmac), so stamps generated by either path verify under both.
// Bash-compat regression test in controller_test.cpp guards this.
//======================================================================================================
#ifndef HMAC_SHA256_HPP
#define HMAC_SHA256_HPP

#include <openssl/hmac.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <string.h>

namespace tt {

// HMAC-SHA256(secret, data) → 64-byte lowercase hex digest.
// hex_out must point to a buffer of at least 65 bytes (64 hex digits + NUL).
// Returns 1 on success, 0 on openssl failure.
//
// `data` may contain arbitrary bytes; length is taken from strlen() since
// the canonical bodies this signs are NUL-terminated text. For binary
// data, use the lower-level HMAC() call directly.
static inline int hmac_sha256_hex(const char* secret, const char* data, char* hex_out) {
    if (!secret || !data || !hex_out) return 0;

    unsigned char raw[32];
    unsigned int  raw_len = 0;
    if (!HMAC(EVP_sha256(),
              secret, (int)strlen(secret),
              (const unsigned char*)data, strlen(data),
              raw, &raw_len)) {
        return 0;
    }
    if (raw_len != 32) return 0;

    static const char hex[] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        hex_out[2*i  ] = hex[raw[i] >> 4];
        hex_out[2*i+1] = hex[raw[i] & 0x0F];
    }
    hex_out[64] = '\0';
    return 1;
}

// SHA-256 of a file via openssl EVP, in-process. Reads in 64KB chunks so
// memory cost is bounded for any file size.
//
// hex_out must point to a buffer of at least `hex_cap` bytes; this writes
// 64 lowercase hex digits + NUL. Returns 1 on success, 0 if file open
// failed, EVP setup failed, or hex_cap < 65.
static inline int sha256_file_hex_inproc(const char* path, char* hex_out, size_t hex_cap) {
    if (!path || !hex_out || hex_cap < 65) return 0;

    FILE* f = fopen(path, "rb");
    if (!f) return 0;

    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    if (!ctx) {
        fclose(f);
        return 0;
    }
    if (EVP_DigestInit_ex(ctx, EVP_sha256(), NULL) != 1) {
        EVP_MD_CTX_free(ctx);
        fclose(f);
        return 0;
    }

    unsigned char buf[65536];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
        if (EVP_DigestUpdate(ctx, buf, n) != 1) {
            EVP_MD_CTX_free(ctx);
            fclose(f);
            return 0;
        }
    }
    fclose(f);

    unsigned char raw[32];
    unsigned int  raw_len = 0;
    if (EVP_DigestFinal_ex(ctx, raw, &raw_len) != 1 || raw_len != 32) {
        EVP_MD_CTX_free(ctx);
        return 0;
    }
    EVP_MD_CTX_free(ctx);

    static const char hex[] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        hex_out[2*i  ] = hex[raw[i] >> 4];
        hex_out[2*i+1] = hex[raw[i] & 0x0F];
    }
    hex_out[64] = '\0';
    return 1;
}

} // namespace tt

#endif // HMAC_SHA256_HPP
