// Copyright (c) 2026 Jennifer Lewis. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
// See LICENSE file in the project root for full license text.

//======================================================================================================
// [FILE]_[MemHeaders/OmsFieldRegistry.hpp]
//------------------------------------------------------------------------------------------------------
// [TAG]_[[ENGINE] [OMS_DRAINER] [FRAMEWORK_DISCIPLINE] [PERSISTENCE]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[the canonical OMS field SSoT — 33 8-tuple rows driving INIT/RESET/PERSIST views via RESET_KIND x STORAGE_KIND x PERSIST_KIND token-paste; the 10-row PERSIST view IS the snapshot OMS wire block (count-pinned)]
// [CONTAINS]
//   - [STRUCT]_[OmsInitCtx]   (+ OmsResetCtx + _oms_now_us ride)
//   - [REGISTRY]_[FOREACH_OMS_FIELD]
//   - [REGISTRY]_[FOREACH_OMS_PER_SLOT_FIELD]   (both registries' count sentinels + 3 asserts ride this block)
//   - [MACRO]_[OMS_PROJECT_*]   (INIT / RESET / PERSIST / PER_SLOT dispatch views)
//   - [FUNCTION]_[_oms_init_value_fields]   (+ _oms_reset_value_fields)
//   - [MACRO]_[OMS_*_AUTOPOPULATE]
// [REFERENCE]_[DESIGN_SPEC]_[[registry-tuple-as-single-source-of-truth] [heterogeneous-registry-pattern] [wire-format-byte-preservation-discipline]]
// [REFERENCE]_[INVARIANT]_[[H9] [H14]]
//======================================================================================================
// Single canonical X-macro registry covering OMS-level scalar fields with
// rich per-field attributes that drive THREE derived views via FOUR
// orthogonal dispatch axes:
//
//   FOREACH_OMS_FIELD(X)
//
//   Tuple: X(NAME, TYPE, INIT, RESET, RESET_KIND, STORAGE_KIND, PERSIST_KIND, STORAGE_MASK)
//
//   Derived views generated by per-consumer X-macro extractors:
//     INIT  view  — _oms_init_value_fields<F>(oms, ctx)   (boot OrderManager_Init)
//     RESET view  — _oms_reset_value_fields<F>(oms, ctx)  (paper-reset)
//     PERSIST view — FOREACH_OMS_FIELD(OMS_PROJECT_PERSIST_*) at ShardedSnapshotPersist save/load
//
//   Dispatch axes (compile-time token-paste):
//     RESET_KIND ∈ {DO_RESET, SKIP_RESET}
//     STORAGE_KIND ∈ {DIRECT, BIT, MULTI_BIT, ATOMIC}
//     PERSIST_KIND ∈ {PERSIST, SKIP_PERSIST}
//
//   STORAGE_KIND determines how the field is read/written:
//     DIRECT    — plain field assignment `_oms->name = (TYPE)(EXPR);`
//     BIT       — bit-set/clear in `_oms->oms_state_flags` via STORAGE_MASK
//     MULTI_BIT — K-state slot write in `_oms->oms_state_flags` via MBS_SET_U8
//                  (slot mask in STORAGE_MASK; shift derived via __builtin_ctz)
//     ATOMIC    — `_oms->name.store((TYPE)(EXPR), std::memory_order_relaxed)`
//
//   PERSIST_KIND determines wire format presence:
//     PERSIST      — saved/loaded as TYPE bytes (for BIT/MULTI_BIT: extract → save as TYPE;
//                     load as TYPE → insert)
//     SKIP_PERSIST — not in snapshot wire format
//
//   STORAGE_MASK: bit mask for BIT (single bit); slot mask for MULTI_BIT (multi-bit);
//                  0 for DIRECT/ATOMIC.
//
// v5.15.5.C.3 Phase 3b — extensions over the v5.15.5.C.2 (S3a-W) parallel
// FOREACH_OMS_PERSIST_FIELD registry:
//   (A) Absorbs FOREACH_OMS_PERSIST_FIELD via the PERSIST view projection;
//       legacy registry deleted (single canonical OMS field source of truth).
//   (B) Adds 3-bit STORAGE_KIND axis enabling registry-driven dispatch over
//       single-bit flags (LIVE_TRADING / PARTIAL_EXIT_ENABLED bits in
//       oms_state_flags), multi-bit slots (EVENT_LOG_MODE 2-bit slot),
//       atomics (flatten_pending / recovery_until_us / total_*), and direct
//       field reads/writes. Layer 2 (special-case scalars) + Layer 3
//       (atomic stores) of the prior AUTOPOPULATE collapse into the
//       registry walk — 8 layers → 5 layers.
//   (C) Adds 2-bit PERSIST_KIND axis orthogonal to STORAGE_KIND. Previously
//       conflated (the BIT enum value implied PERSIST; DIRECT implied
//       PERSIST; SKIP_PERSIST was its own value). Now each combination is
//       independently expressible: BIT + PERSIST (kill_switch_tripped wire
//       byte 4), BIT + SKIP_PERSIST (LIVE_TRADING/PARTIAL_EXIT_ENABLED — cfg
//       derived; not persisted), MULTI_BIT + SKIP_PERSIST (EVENT_LOG_MODE
//       cfg derived), ATOMIC + SKIP_PERSIST (observability counters).
//   (D) Closes TECH_DEBT-012 (FOREACH_OMS_STATE registry — full canonical
//       multi-target dispatch over INIT/RESET/PERSIST views).
//   (E) Wire-format rows ordered to match snapshot v8 byte stream (rows
//       7-16 below); SKIP_PERSIST rows interleaved by semantic grouping
//       (HOT, cfg-derived, observability, COLD).
//
// FINDING A (PARTIAL_EXIT_ENABLED bit into registry; v5.15.5.C.3):
//   Pre: engine boot called `OMS_STATE_FLAG_SET(PARTIAL_EXIT_ENABLED)`
//        externally after OrderManager_Init returned (Class-18 mirror at
//        the external SET site).
//   Post: row in registry (BIT + SKIP_PERSIST); `partial_exit_enabled`
//         passed as OrderManager_Init parameter; external SET call dropped.
//
// FINDING A' (EVENT_LOG_MODE 2-bit slot via MULTI_BIT; v5.15.5.C.3):
//   Pre: `int event_log_mode;` field on OrderManagerState (4 bytes + pad);
//        Layer 2 special-case in AUTOPOPULATE for `_oms->event_log_mode = ...`.
//   Post: 2-bit slot at bits 3-4 of `oms_state_flags` (4 bytes saved per OMS;
//         registry-driven via MULTI_BIT dispatch). 2nd codebase application
//         of multi-bit-state-encoding-pattern.md (after `last_exit_predicted_meta[16]`).
//         The "2+ applications" promotion threshold WAS hit — the MBS
//         discipline is codified as H14.
//
// FINDING B skipped 2026-05-13 (packed OmsInitCtx boot_flags): stack-only
// helper struct with brief lifetime (~1µs at boot); byte savings symbolic;
// registry-row verbosity from BITMAP_IS_SET/MBS_GET_U8 expansion would hurt
// per-row readability. OmsInitCtx uses plain unpacked fields. Finding A'
// already hits 2-app promotion threshold without B.
//
// Cross-references:
//   DESIGN_SPECS/registry-tuple-as-single-source-of-truth.md (8-col tuple expansion)
//   DESIGN_SPECS/heterogeneous-registry-pattern.md (3-axis dispatch via token paste)
//   DESIGN_SPECS/autopopulate-pattern-for-production-caller-class.md (companion macros)
//   DESIGN_SPECS/x-macro-registry-with-presence-dispatch.md (SKIP_* dispatch)
//   DESIGN_SPECS/bitmap-flag-api.md (BIT-kind references mask constants)
//   DESIGN_SPECS/multi-bit-state-encoding-pattern.md (MULTI_BIT slot dispatch)
//   DESIGN_SPECS/wire-format-byte-preservation-discipline.md (PERSIST row ordering)
//   (+ the X-macro-registry / parity-tested-by-construction / structural-fix-
//    preferred / BITMAP_* hybrid / AUTOPOPULATE-companion / templated-helpers
//    disciplines — per the .B.7 precedent)
//   v5.15.5.B.7 FOREACH_NODE_CTX_FIELD (sister registry; unified init/reset tuple precedent)
//   v5.15.5.C.2.1 FOREACH_OMS_META_SLOT (per-slot multi-bit; struct-level analog: this header's EVENT_LOG_MODE)
//======================================================================================================
#ifndef OMS_FIELD_REGISTRY_HPP
#define OMS_FIELD_REGISTRY_HPP

#include <stdint.h>
#include <chrono>
#include <atomic>
#include <cstdio>
#include "../FixedPoint/FixedPointN.hpp"  // FPN_Binary<F> — needed for OmsInitCtx<F>/OmsResetCtx<F> fields by value
#include "BitmapMacros.hpp"
#include "OmsStateFlagRegistry.hpp"       // MASK_OMS_STATE_* + SHIFT_OMS_STATE_* constants

// Forward declarations — OmsFieldRegistry.hpp is included BEFORE
// OrderManagerState<F> is defined in OrderManager.hpp.
// Templated helpers below take `OrderManagerState<F>*` — pointer-to-incomplete
// is OK at template declaration; full type required at instantiation (which
// happens at OrderManager_Init's body where the struct is complete).
namespace tt {
    template <unsigned F> struct OrderManagerState;
    template <unsigned F> struct ExchangeAdapter;
    template <unsigned F> struct FoldResult;
    struct ShardedTradeLog;
}  // namespace tt

namespace tt {

//======================================================================
// [STRUCT]_[OmsInitCtx]
//----------------------------------------------------------------------
// [TAG]_[[ENGINE] [OMS_DRAINER] [BOOT_TIME]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[boot-init + paper-reset context structs (OmsResetCtx + the _oms_now_us helper ride) — plain unpacked fields (Finding B); field order MUST match the AUTOPOPULATE aggregate initializer]
//======================================================================
// [CODE]
//======================================================================
//------------------------------------------------------------------
// [SECTION]_[HELPER: NOW_US — wall-clock microseconds since epoch]
//------------------------------------------------------------------
// Used as INIT_VALUE / RESET_VALUE for `paper_session_start_us`. Evaluated
// at the AUTOPOPULATE expansion site (each evaluation captures fresh time).
inline uint64_t _oms_now_us() {
    return (uint64_t)std::chrono::duration_cast<std::chrono::microseconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();
}

//------------------------------------------------------------------
// [SECTION]_[OmsInitCtx<F> + OmsResetCtx<F> — context structs for templated helpers]
//------------------------------------------------------------------
// OmsInitCtx<F>: boot-time init args. Constructed by OMS_INIT_AUTOPOPULATE
// macro at the call site (currently OrderManager_Init only); passed by
// const-ref to _oms_init_value_fields<F>. Stack-allocated, lives ~1µs at boot.
//
// PLAIN UNPACKED fields chosen over packed boot_flags (Finding B skipped
// 2026-05-13): stack-only with brief lifetime → byte savings don't compound,
// but registry-row verbosity from BITMAP_IS_SET/MBS_GET_U8 expansion would
// hurt readability per row. Plain fields make `ctx.live_trading` etc. clean
// 1-line registry expressions.
//
// Field order MUST match OMS_INIT_AUTOPOPULATE's aggregate initializer.
//======================================================================================================
template <unsigned F>
struct OmsInitCtx {
    const ExchangeAdapter<F>& adapter;
    int                       live_trading;          // 0/1 — boolean
    int                       partial_exit_enabled;  // 0/1 — boolean (NEW v5.15.5.C.3 Finding A)
    int                       event_log_mode;        // 0..3 — K-state (NEW MULTI_BIT slot v5.15.5.C.3 Finding A')
    Money                             starting_balance;
    // v5.15.5.F.4c.3 WIP2d-1.B.1 — fee_rate DELETED. Per-core fee_rate now lives on
    // cfg.nodes[c].fee_rate_maker/_taker; flows through Order pre_resolved at submit.
    const char*               event_log_path;
};

// OmsResetCtx<F>: paper-reset args. Only ctx fields evaluated in DO_RESET
// rows need to be present (SKIP_RESET rows discard the RESET expression at
// preprocessor-dispatch time — never evaluated). Today: only ctx.starting_balance
// referenced (by balance, ks_peak_balance row resets).
template <unsigned F>
struct OmsResetCtx {
    Money starting_balance;
};
//======================================================================
// [END_CODE]
//======================================================================
// [DERIVED]
// [ORIGIN]_[AUTO]
// [UPDATED]_[2026-07-18]
// [SIZE]_[64B]
// [ALIGN]_[16]
// [CACHE_LINES]_[1]
// [STRADDLE]_[none]
//======================================================================
// [END_STRUCT]_[OmsInitCtx]
//======================================================================

//======================================================================
// [REGISTRY]_[FOREACH_OMS_FIELD]
//----------------------------------------------------------------------
// [TAG]_[[ENGINE] [OMS_DRAINER] [FRAMEWORK_DISCIPLINE] [PERSISTENCE]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[33 8-tuple rows in 9 semantic groups (substrate -> BIT/MBS cfg-derived -> HOT -> the 10 wire-ordered PERSIST rows -> cfg-derived -> masks -> adapter -> atomics -> COLD)]
// [COLUMN]_[NAME]_[field name on OrderManagerState (or bit/slot name for BIT/MULTI_BIT)]
// [COLUMN]_[type]_[C++ type; cast applied at write site]
// [COLUMN]_[INIT]_[boot value; ctx.<arg> forms reference OmsInitCtx]
// [COLUMN]_[RESET]_[paper-reset value; only evaluated for DO_RESET rows]
// [COLUMN]_[RESET_KIND]_[DO_RESET | SKIP_RESET]
// [COLUMN]_[STORAGE_KIND]_[DIRECT | BIT | MULTI_BIT | ATOMIC]
// [COLUMN]_[PERSIST_KIND]_[PERSIST | SKIP_PERSIST]
// [COLUMN]_[STORAGE_MASK]_[MASK_OMS_STATE_* for BIT/MULTI_BIT; 0 otherwise]
// [REFERENCE]_[CLASS]_[[5] [27]]
// [REFERENCE]_[INVARIANT]_[H9]
// [REFERENCE]_[DESIGN_SPEC]_[[aggressive-memory-reduction-techniques.md] [slot-state-foreach-registry-with-storage-routing.md] [wire-format-byte-preservation-discipline.md]]
//======================================================================
// [CODE]
//======================================================================
#define FOREACH_OMS_FIELD(X)                                                                                                                            \
    /* ============================================================================================ */                                                  \
    /* [1] SUBSTRATE — oms_state_flags MUST be initialized to 0 before BIT/MULTI_BIT rows below       */                                                  \
    /*     OR their bits into it. SKIP_RESET preserves LIVE_TRADING + PARTIAL_EXIT_ENABLED across     */                                                  \
    /*     paper-reset (those are cfg-derived; kill_switch_tripped bit clearing happens via its own   */                                                  \
    /*     DO_RESET BIT row below).                                                                  */                                                  \
    /* ============================================================================================ */                                                  \
    X(oms_state_flags,        uint8_t,            0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [2] BIT + MULTI_BIT cfg-derived rows — set bits/slots in oms_state_flags                       */                                                  \
    /* ============================================================================================ */                                                  \
    /* LIVE_TRADING bit (Finding A — moved into registry; was Layer 2 special-case)                  */                                                  \
    X(live_trading,           int,                ctx.live_trading,             0,                            SKIP_RESET, BIT,       SKIP_PERSIST, MASK_OMS_STATE_LIVE_TRADING)        \
    /* PARTIAL_EXIT_ENABLED bit (Finding A — moved into registry; was engine-post-Init external SET) */                                                  \
    X(partial_exit_enabled,   int,                ctx.partial_exit_enabled,     0,                            SKIP_RESET, BIT,       SKIP_PERSIST, MASK_OMS_STATE_PARTIAL_EXIT_ENABLED) \
    /* EVENT_LOG_MODE 2-bit slot (Finding A' — multi-bit struct compaction; saves 4 bytes)           */                                                  \
    X(event_log_mode,         int,                ctx.event_log_mode,           0,                            SKIP_RESET, MULTI_BIT, SKIP_PERSIST, MASK_OMS_STATE_EVENT_LOG_MODE)       \
    /* ============================================================================================ */                                                  \
    /* [3] HOT cluster scalars (drainer reads every cycle)                                            */                                                  \
    /* ============================================================================================ */                                                  \
    X(order_bitmap,           uint16_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(next_order_id,          uint64_t,           1,                            1,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [4] WIRE-FORMAT-ORDERED PERSIST rows — snapshot v8 byte positions 1..10                       */                                                  \
    /*     CLAUDE.md item 15 + DESIGN_SPECS/wire-format-byte-preservation-discipline.md.             */                                                  \
    /*     Row order in FOREACH determines emission order in PERSIST view's save/load walks.         */                                                  \
    /* ============================================================================================ */                                                  \
    /* Wire position 1-2: bank state (Phase 2.1 P&L leak anchor)                                     */                                                  \
    X(balance,                Money,                     ctx.starting_balance,         ctx.starting_balance,         DO_RESET,   DIRECT,    PERSIST,      0)    \
    X(realized_pnl,           Money,                     Money_Zero(),                 Money_Zero(),                DO_RESET,   DIRECT,    PERSIST,      0)    \
    /* Wire position 3: kill switch peak                                                             */                                                  \
    X(ks_peak_balance,        Money,                     ctx.starting_balance,         ctx.starting_balance,         DO_RESET,   DIRECT,    PERSIST,      0)    \
    /* Wire position 4: kill_switch_tripped (BIT in oms_state_flags; persisted as int 4 bytes)       */                                                  \
    X(kill_switch_tripped,    int,                0,                            0,                            DO_RESET,   BIT,       PERSIST,      MASK_OMS_STATE_KILL_SWITCH_TRIPPED) \
    /* Wire position 5-7: fee accumulators (v5.5.6 Class-5 recurring-bug close)                      */                                                  \
    X(total_fees,             Money,                     Money_Zero(),                 Money_Zero(),                DO_RESET,   DIRECT,    PERSIST,      0)    \
    X(total_maker_fees,       Money,                     Money_Zero(),                 Money_Zero(),                DO_RESET,   DIRECT,    PERSIST,      0)    \
    X(total_taker_fees,       Money,                     Money_Zero(),                 Money_Zero(),                DO_RESET,   DIRECT,    PERSIST,      0)    \
    /* Wire position 8-9: maker/taker fill counters                                                  */                                                  \
    X(maker_fills_count,      uint32_t,           0,                            0,                            DO_RESET,   DIRECT,    PERSIST,      0)    \
    X(taker_fills_count,      uint32_t,           0,                            0,                            DO_RESET,   DIRECT,    PERSIST,      0)    \
    /* Wire position 10: paper session start anchor (v5.15.5.C.3 Phase 2 — archive dir naming)       */                                                  \
    X(paper_session_start_us, uint64_t,           tt::_oms_now_us(),            tt::_oms_now_us(),            DO_RESET,   DIRECT,    PERSIST,      0)    \
    /* ============================================================================================ */                                                  \
    /* [5] SKIP_PERSIST cfg-derived rows (fee rates, kill switch limits)                              */                                                  \
    /* ============================================================================================ */                                                  \
    /* v5.15.5.F.4c.3 WIP2d-1.B.1 — fee_rate / fee_rate_maker / fee_rate_taker / slippage_pct rows DELETED. */ \
    /* Per Class 27 closure: scalar cfg-mirror caches eliminated. Per-core values live on cfg.nodes[c]; */ \
    /* per-Order via pre_resolved (Order_BindPreResolved at submit). last_exit_fee[pslot] sibling array */ \
    /* stores the authoritative per-fill exit_fee (set by HandleFill SELL; consumed by DrainPostFill). */ \
    X(ks_min_balance,         Money,                     Money_Zero(),                 Money_Zero(),                SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(ks_max_drawdown_pct,    Money,                     Money_Zero(),                 Money_Zero(),                SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(ks_trips_total,         uint64_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [6] SKIP_PERSIST per-cycle observability masks (cleared inside the tick; no session reset)    */                                                  \
    /* ============================================================================================ */                                                  \
    X(last_closed_mask,       uint16_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(last_opened_mask,       uint16_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(last_exit_predicted_bitmap, uint16_t,       0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* v5.15.5.C.4 Phase J — was_win extracted from FillRecord to cross-slot bitmap (Technique 3 of aggressive-memory-reduction-techniques.md) */         \
    X(last_was_win_bitmap,    uint16_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* v5.15.5.C.5 — is_maker reverted from Position SKIP_PERSIST to OMS-level cross-slot bitmap per slot-state-foreach-registry-with-storage-routing.md */ \
    X(last_is_maker_bitmap,   uint16_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [7] Adapter struct copy (was Layer 2 special-case; now DIRECT row)                             */                                                  \
    /* ============================================================================================ */                                                  \
    X(adapter,                ExchangeAdapter<F>, ctx.adapter,                  ctx.adapter,                  SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [8] SKIP_PERSIST atomics (cross-thread observability counters; was Layer 3 explicit stores)   */                                                  \
    /*     total_* atomics DO_RESET per v5.5.6 Class-5 recurring-bug close (paper-reset wipes them). */                                                  \
    /*     flatten_pending / recovery_until_us SKIP_RESET (steady-state cross-thread state, not      */                                                  \
    /*     session-scoped; preserves emergency-flatten coordination across paper-reset boundary).    */                                                  \
    /* ============================================================================================ */                                                  \
    X(flatten_pending,        int,                0,                            0,                            SKIP_RESET, ATOMIC,    SKIP_PERSIST, 0)    \
    X(recovery_until_us,      uint64_t,           0,                            0,                            SKIP_RESET, ATOMIC,    SKIP_PERSIST, 0)    \
    X(total_submitted,        uint64_t,           0,                            0,                            DO_RESET,   ATOMIC,    SKIP_PERSIST, 0)    \
    X(total_filled,           uint64_t,           0,                            0,                            DO_RESET,   ATOMIC,    SKIP_PERSIST, 0)    \
    X(total_rejected,         uint64_t,           0,                            0,                            DO_RESET,   ATOMIC,    SKIP_PERSIST, 0)    \
    /* ============================================================================================ */                                                  \
    /* [9] SKIP_PERSIST COLD pointers + last_seen_trade_id                                            */                                                  \
    /* ============================================================================================ */                                                  \
    X(calibration_log_file,   FILE*,              nullptr,                      nullptr,                      SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(trade_log,              ShardedTradeLog*,   nullptr,                      nullptr,                      SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)    \
    X(last_seen_trade_id,     uint64_t,           0,                            0,                            SKIP_RESET, DIRECT,    SKIP_PERSIST, 0)
//======================================================================
// [END_CODE]
//======================================================================
// [COMMENT]
//----------------------------------------------------------------------
// Row ordering convention:
//   1. SUBSTRATE row (oms_state_flags) FIRST — BIT/MULTI_BIT rows below
//      depend on this being initialized to 0 before they OR/AND their bits in.
//   2. BIT + MULTI_BIT cfg-derived rows next (SKIP_PERSIST) — set/clear bits
//      in oms_state_flags.
//   3. HOT scalars (order_bitmap, next_order_id) — SKIP_PERSIST.
//   4. WIRE-FORMAT-ORDERED PERSIST rows next (wire positions 1..10 of
//      snapshot v8 stream). PERSIST view's FOREACH walk emits in this order
//      to preserve byte-format compatibility (H9 wire preservation).
//   5. SKIP_PERSIST cfg-derived rows (fee rates, slippage, ks state) — any order.
//   6. SKIP_PERSIST observability rows (exit-fill masks, atomics) — any order.
//   7. SKIP_PERSIST COLD pointers + last_seen_trade_id — any order.
//
// Adding a new OMS-level field: ONE row in this registry. Pick:
//   - RESET_KIND: DO_RESET if session-scoped accumulator; SKIP_RESET if boot-only/cfg-derived.
//   - STORAGE_KIND: DIRECT for normal fields; BIT for single-bit flags in oms_state_flags;
//     MULTI_BIT for K-state slots in oms_state_flags; ATOMIC for std::atomic<T>.
//   - PERSIST_KIND: PERSIST if in snapshot wire format; SKIP_PERSIST otherwise.
//   - STORAGE_MASK: bit/slot mask constant for BIT/MULTI_BIT; 0 for DIRECT/ATOMIC.
//
// SKIP_RESET reasoning per field group (audit trail anchored to incident class):
//   - next_order_id: drainer has in-flight orders; reset risks ID collision with un-drained submits.
//   - adapter:       boot-set struct copy; reset would zero function pointers in live mid-session.
//   - oms_state_flags substrate: reset would wipe LIVE_TRADING + PARTIAL_EXIT_ENABLED bits which
//                                are cfg-derived (not session-scoped); kill_switch_tripped bit reset
//                                handled by its own DO_RESET BIT row.
//   - fee_rate*, slippage_pct:    cfg-derived; same cfg = same rates post-reset.
//   - last_seen_trade_id:         high-watermark must monotonically increase across paper-reset
//                                  (Class 5 recurring-bug — replay safety across reset boundary).
//   - calibration_log_file, trade_log: FILE* / owner pointers; rotation handled at archive capture (Phase 6).
//   - flatten_pending, recovery_until_us: cross-thread CAS atomics; resetting via value-init would race
//                                          with CheckWsStaleness; steady-state state, not session-scoped.
//   - ks_min_balance, ks_max_drawdown_pct, ks_trips_total: cfg-derived limits + trip counter (across-session).
//   - last_closed_mask, last_opened_mask, last_exit_predicted_bitmap: per-cycle state cleared inside the tick;
//     no session-reset needed.
//
// DO_RESET fields = session-scoped accumulator state (Phase 2.1 / Phase 3 / v5.5.6 Class-5 recurring-bug class).
//======================================================================
// [END_REGISTRY]_[FOREACH_OMS_FIELD]
//======================================================================

//======================================================================
// [REGISTRY]_[FOREACH_OMS_PER_SLOT_FIELD]
//----------------------------------------------------------------------
// [TAG]_[[ENGINE] [OMS_DRAINER] [FRAMEWORK_DISCIPLINE]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[5 per-slot scalar rows walked inside the MAX_PORTFOLIO_POSITIONS loop (both registries' count sentinels + 3 asserts ride this block, incl. the ==10 PERSIST wire pin)]
// [COLUMN]_[NAME_OR_ACCESSOR]_[top-level array name (last_realized_return[_i]) or field accessor]
// [COLUMN]_[type]_[C++ type for the cast at write site]
// [COLUMN]_[INIT]_[per-slot boot init value]
// [COLUMN]_[RESET]_[per-slot value at DrainPostFill post-attribution clear]
// [REFERENCE]_[CLASS]_[[27] [30]]
// [REFERENCE]_[DESIGN_SPEC]_[[decision-time-data-binding-pattern.md] [manual-fields-inventory-pattern.md] [slot-state-foreach-registry-with-storage-routing.md] [wire-format-byte-preservation-discipline.md]]
//======================================================================
// [CODE]
//======================================================================
#define FOREACH_OMS_PER_SLOT_FIELD(X)                                                          \
    X(last_realized_return[_i],         double,    0.0,            0.0)                        \
    /* v5.15.5.C.4 Phase G — exit-side fields REMOVED (derived at DrainPostFill).             \
     * v5.15.5.C.4 Phase H — entry-side fields REMOVED (derived at DrainPostFill open-mask).  \
     * v5.15.5.C.4 Phase J — was_win moved to OMS-level last_was_win_bitmap.                  \
     * FillRecord struct DELETED in Phase K.                                                  */ \
    X(last_exit_predicted_p[_i],        double,    0.0,            0.0)                        \
    /* v5.15.5.C.5 — exit_fill_price reverted from Position SKIP_PERSIST to OMS sibling SoA   \
     * per slot-state-foreach-registry-with-storage-routing.md decision tree.                 */ \
    X(last_exit_fill_price[_i],         Money,            Money_Zero(),   Money_Zero())              \
    /* v5.15.5.F.4d Step 7 (§ N.2 of merged plan body) — last_exit_fee[_i] enrollment closes \
     * Class 30 latent drift (field has existed on OmsState since .F.4c.3 r-4 WIP2d-1.B.1     \
     * but was never enrolled in this registry; per-slot reset/init was hand-maintained).     \
     * ⚠ CORRECTED at E.1.2 D-421 — this comment used to promise: "NEW CI Check 8 enforces  \
     * all `\w+[MAX_PORTFOLIO_POSITIONS]` arrays on OmsState are either enrolled here OR     \
     * exempted." THAT TOOL WAS NEVER WRITTEN. There is no CI check on this registry.        \
     * NOTHING stops the 7th per-slot array being added without a row, which is exactly the  \
     * Class 30 drift the row above was added to close. Enrolment here is CONVENTION today.  \
     * The set happens to be complete (6 arrays: 5 enrolled + last_exit_predicted_meta       \
     * exempted via OMS_META_CLEAR) — verified, not assumed — but that is nobody-added-one,  \
     * not enforcement. Tracked TECH_DEBT-274; the real close is the D-421 DOMAIN column,    \
     * which generalises this check to all enrolled registries instead of adding a 9th       \
     * bespoke guard. If you are adding an array HERE: add the row by hand and mean it.      */ \
    X(last_exit_fee[_i],                Money,            Money_Zero(),   Money_Zero())              \
    /* v5.15.5.F.4d Step 7 (§ N.2) — NEW bandit_reward_bps[_i] sibling. Bandit reward         \
     * attribution: HandleFill SELL writes per-slot reward_bps for downstream DrainPostFill   \
     * consumption (replaces Class 27 cfg-mirror recompute pattern; reward stays bound to    \
     * the slot through trade lifecycle per decision-time-data-binding-pattern.md sibling-   \
     * array carrier variant).                                                                */ \
    X(bandit_reward_bps[_i],            double,    0.0,            0.0)

//------------------------------------------------------------------
// [SECTION]_[COMPILE-TIME COUNT SENTINELS — both registries]
//------------------------------------------------------------------
#define _OMS_FIELD_COUNT_ONE(name, type, init, reset, rkind, skind, pkind, smask) +1
constexpr int FOREACH_OMS_FIELD_COUNT =
    0 FOREACH_OMS_FIELD(_OMS_FIELD_COUNT_ONE);
#undef _OMS_FIELD_COUNT_ONE

#define _OMS_PER_SLOT_COUNT_ONE(name, type, init, reset) +1
constexpr int FOREACH_OMS_PER_SLOT_FIELD_COUNT =
    0 FOREACH_OMS_PER_SLOT_FIELD(_OMS_PER_SLOT_COUNT_ONE);
#undef _OMS_PER_SLOT_COUNT_ONE

// [ASSERT]_[REGISTRY_COVERAGE]_[FOREACH_OMS_FIELD_COUNT >= 30]
static_assert(FOREACH_OMS_FIELD_COUNT >= 30,
              "FOREACH_OMS_FIELD must keep at least the v5.15.5.C.3 set "
              "(30+ scalar entries: substrate + 3 BIT/MULTI_BIT + HOT + 10 PERSIST wire + "
              "cfg-derived + observability masks + adapter + 5 atomics + 3 COLD). "
              "Removing entries requires explicit justification.");

// v5.15.5.C.3 Phase 10 (/parity-check LOW-2 close): lock PERSIST view row
// count to 10 — wire format snapshot v8 expects exactly 10 PERSIST-kind
// rows (balance, realized_pnl, ks_peak_balance, kill_switch_tripped,
// total_fees, total_maker_fees, total_taker_fees, maker_fills_count,
// taker_fills_count, paper_session_start_us). Adding/removing a PERSIST
// row CHANGES the snapshot wire format → SHARDED_SNAPSHOT_VERSION bump
// + loader-side migration required. Static_assert catches accidental
// count drift at compile time.
#define _OMS_PERSIST_COUNT_PERSIST       +1
#define _OMS_PERSIST_COUNT_SKIP_PERSIST  +0
#define _OMS_FIELD_PERSIST_COUNT_ONE(name, type, init, reset, rkind, skind, pkind, smask) \
    _OMS_PERSIST_COUNT_##pkind
constexpr int FOREACH_OMS_FIELD_PERSIST_COUNT =
    0 FOREACH_OMS_FIELD(_OMS_FIELD_PERSIST_COUNT_ONE);
#undef _OMS_FIELD_PERSIST_COUNT_ONE
#undef _OMS_PERSIST_COUNT_PERSIST
#undef _OMS_PERSIST_COUNT_SKIP_PERSIST
// [ASSERT]_[REGISTRY_COVERAGE]_[FOREACH_OMS_FIELD_PERSIST_COUNT == 10 — the snapshot OMS wire pin]
static_assert(FOREACH_OMS_FIELD_PERSIST_COUNT == 10,
              "Snapshot v8 wire format expects EXACTLY 10 PERSIST-kind fields. "
              "Adding/removing a PERSIST row in FOREACH_OMS_FIELD requires "
              "SHARDED_SNAPSHOT_VERSION bump + loader migration. See "
              "DESIGN_SPECS/wire-format-byte-preservation-discipline.md.");

// v5.15.5.F.4d Step 7 (§ N.2) — per-slot scalar count bumped 3 → 5 via 2-row extension:
//   + last_exit_fee[16] (closes Class 30 latent drift from .F.4c.3 r-4 — field existed but
//     wasn't enrolled in this registry; reset path was hand-maintained)
//   + bandit_reward_bps[16] (NEW; per-slot bandit reward sibling for DrainPostFill consumer)
// [ASSERT]_[REGISTRY_COVERAGE]_[FOREACH_OMS_PER_SLOT_FIELD_COUNT >= 5]
static_assert(FOREACH_OMS_PER_SLOT_FIELD_COUNT >= 5,
              "FOREACH_OMS_PER_SLOT_FIELD must keep the 5 per-slot scalar entries "
              "(last_realized_return + last_exit_predicted_p + last_exit_fill_price + "
              "last_exit_fee + bandit_reward_bps). last_exit_fee enrolled at .F.4d to close "
              "Class 30 latent drift; bandit_reward_bps NEW at .F.4d for bandit reward attribution. "
              "FillRecord struct DELETED in C.4 Phase K; SKIP_PERSIST Position fields "
              "reverted to OMS siblings in C.5 per slot-state-foreach decision tree.");
//======================================================================
// [END_CODE]
//======================================================================
// [COMMENT]
//----------------------------------------------------------------------
// Separate from FOREACH_OMS_FIELD because per-slot fields use a looped
// access pattern over MAX_PORTFOLIO_POSITIONS. Walked inside a
// `for (int _i = 0; _i < MAX_PORTFOLIO_POSITIONS; ++_i)` loop in
// AUTOPOPULATE Layer 2.
//
// `last_exit_predicted_meta[i]` is cleared via OMS_META_CLEAR helper
// (defined in OmsExitPredictorMetaRegistry.hpp) — handled separately in
// the per-slot AUTOPOPULATE expansion below.
//======================================================================
// [END_REGISTRY]_[FOREACH_OMS_PER_SLOT_FIELD]
//======================================================================

}  // namespace tt

//----------------------------------------------------------------------
// [MACRO]_[OMS_PROJECT_*]
// [TAG]_[[ENGINE] [OMS_DRAINER] [FRAMEWORK_DISCIPLINE]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[the token-paste dispatch views — INIT (STORAGE_KIND), RESET (RESET_KIND x STORAGE_KIND), PERSIST (4-phase save/declare/read/commit; unimplemented combos static_assert(false)), PER_SLOT]
//----------------------------------------------------------------------

//------------------------------------------------------------------
// [SECTION]_[DISPATCH MACROS — INIT view (STORAGE_KIND token-paste)]
//------------------------------------------------------------------
// INIT walk runs at boot from _oms_init_value_fields helper. Every row gets
// initialized regardless of RESET_KIND; dispatch on STORAGE_KIND determines
// HOW the init value is written (plain assign / bit set/clear / multi-bit
// slot write / atomic store).

#define OMS_PROJECT_INIT(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_INIT_##skind(name, type, init, smask)

// DIRECT: plain field assignment. Cast (type) handles narrowing/widening.
#define OMS_PROJECT_INIT_DIRECT(name, type, init, smask) \
    _oms->name = (type)(init);

// BIT: set or clear the masked bit in oms_state_flags based on init truthiness.
// Trailing `;` after the do-while so the macro is SELF-TERMINATING when chained
// inside FOREACH_OMS_FIELD's per-row expansion (each row's expansion sits in
// statement sequence; non-terminating do-while-0 leaks into the next row's start).
#define OMS_PROJECT_INIT_BIT(name, type, init, smask)                                 \
    do {                                                                              \
        if ((int)(init)) _oms->oms_state_flags |=  (uint8_t)(tt::smask);              \
        else             _oms->oms_state_flags &= (uint8_t)(~(uint8_t)(tt::smask));   \
    } while (0);

// MULTI_BIT: insert K-state value into slot (shift derived via __builtin_ctz of mask).
// MBS_SET_U8 is itself a do-while; trailing `;` self-terminates this row.
#define OMS_PROJECT_INIT_MULTI_BIT(name, type, init, smask)                           \
    MBS_SET_U8(_oms->oms_state_flags, (uint8_t)(tt::smask),                           \
               (int)__builtin_ctz((unsigned)(tt::smask)), (init));

// ATOMIC: __atomic_store via std::atomic<T>::store with relaxed ordering.
#define OMS_PROJECT_INIT_ATOMIC(name, type, init, smask) \
    _oms->name.store((type)(init), std::memory_order_relaxed);

//------------------------------------------------------------------
// [SECTION]_[DISPATCH MACROS — RESET view (RESET_KIND × STORAGE_KIND token-paste)]
//------------------------------------------------------------------
// RESET walk runs at paper-reset from _oms_reset_value_fields helper.
// Dispatch on RESET_KIND first (SKIP_RESET = no emission); for DO_RESET,
// further dispatch on STORAGE_KIND to determine HOW the reset value is written.

#define OMS_PROJECT_RESET(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_RESET_##rkind##_##skind(name, type, reset, smask)

// SKIP_RESET × all STORAGE_KIND — no emission (reset expression never evaluated).
#define OMS_PROJECT_RESET_SKIP_RESET_DIRECT(name, type, reset, smask)
#define OMS_PROJECT_RESET_SKIP_RESET_BIT(name, type, reset, smask)
#define OMS_PROJECT_RESET_SKIP_RESET_MULTI_BIT(name, type, reset, smask)
#define OMS_PROJECT_RESET_SKIP_RESET_ATOMIC(name, type, reset, smask)

// DO_RESET × DIRECT: plain assignment with cast.
#define OMS_PROJECT_RESET_DO_RESET_DIRECT(name, type, reset, smask) \
    _oms->name = (type)(reset);

// DO_RESET × BIT: set/clear bit based on reset truthiness.
// Trailing `;` self-terminates within FOREACH chain (see OMS_PROJECT_INIT_BIT note).
#define OMS_PROJECT_RESET_DO_RESET_BIT(name, type, reset, smask)                       \
    do {                                                                               \
        if ((int)(reset)) _oms->oms_state_flags |=  (uint8_t)(tt::smask);              \
        else              _oms->oms_state_flags &= (uint8_t)(~(uint8_t)(tt::smask));   \
    } while (0);

// DO_RESET × MULTI_BIT: insert K-state value into slot.
#define OMS_PROJECT_RESET_DO_RESET_MULTI_BIT(name, type, reset, smask)                 \
    MBS_SET_U8(_oms->oms_state_flags, (uint8_t)(tt::smask),                            \
               (int)__builtin_ctz((unsigned)(tt::smask)), (reset));

// DO_RESET × ATOMIC: atomic store with relaxed ordering.
#define OMS_PROJECT_RESET_DO_RESET_ATOMIC(name, type, reset, smask) \
    _oms->name.store((type)(reset), std::memory_order_relaxed);

//------------------------------------------------------------------
// [SECTION]_[DISPATCH MACROS — PERSIST view (PERSIST_KIND × STORAGE_KIND token-paste)]
//------------------------------------------------------------------
// Four phases for the snapshot save/load lifecycle:
//   OMS_PROJECT_PERSIST_SAVE     — at save: emit fwrite of the wire value
//   OMS_PROJECT_PERSIST_DECLARE  — at load: declare tmp_<name> local for each persist row
//   OMS_PROJECT_PERSIST_READ     — at load: fread into tmp_<name>
//   OMS_PROJECT_PERSIST_COMMIT   — at load: assign tmp_<name> back to OMS (DIRECT) or
//                                  set bit/slot in oms_state_flags (BIT/MULTI_BIT)
//
// Dispatch on PERSIST_KIND first (SKIP_PERSIST = no emission).
// PERSIST × STORAGE_KIND combinations:
//   PERSIST × DIRECT     — used by balance/realized_pnl/ks_peak_balance/totals/counters/paper_session_start_us
//   PERSIST × BIT        — used by kill_switch_tripped (extract bit at save; set/clear at commit)
//   PERSIST × MULTI_BIT  — not used today; static_assert(false) IF a future row uses this combo
//                          (first implementer designs the wire format: presumably save full int value
//                          via MBS_GET_U8 → fwrite; load → MBS_SET_U8 commit)
//   PERSIST × ATOMIC     — not used today; static_assert(false) IF a future row uses this combo
//                          (first implementer designs ordering: presumably atomic_load at save,
//                          atomic_store at commit, with documented memory_order)
//
// CALL FORMS at ShardedSnapshotPersist.hpp:
//   FOREACH_OMS_FIELD(OMS_PROJECT_PERSIST_SAVE)     — save site
//   FOREACH_OMS_FIELD(OMS_PROJECT_PERSIST_DECLARE)  — load tmp decl block
//   FOREACH_OMS_FIELD(OMS_PROJECT_PERSIST_READ)     — load fread block
//   FOREACH_OMS_FIELD(OMS_PROJECT_PERSIST_COMMIT)   — load commit block
//
// Caller scope must have:
//   - `state` — EventLoopState<F>* (save uses state->oms->; load uses state->oms->)
//   - `f`     — FILE* opened wb / rb
//   - `fail:` label (save site only — goto fail on fwrite failure)
//   - For load: caller's enclosing function returns 0 on fread failure

// ---- SAVE ----
#define OMS_PROJECT_PERSIST_SAVE(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_PERSIST_SAVE_##pkind##_##skind(name, type, smask)

#define OMS_PROJECT_PERSIST_SAVE_SKIP_PERSIST_DIRECT(name, type, smask)
#define OMS_PROJECT_PERSIST_SAVE_SKIP_PERSIST_BIT(name, type, smask)
#define OMS_PROJECT_PERSIST_SAVE_SKIP_PERSIST_MULTI_BIT(name, type, smask)
#define OMS_PROJECT_PERSIST_SAVE_SKIP_PERSIST_ATOMIC(name, type, smask)

#define OMS_PROJECT_PERSIST_SAVE_PERSIST_DIRECT(name, type, smask)                       \
    {                                                                                     \
        type _v_save_##name = state->oms->name;                                           \
        if (fwrite(&_v_save_##name, sizeof(type), 1, f) != 1) goto fail;                  \
    }

#define OMS_PROJECT_PERSIST_SAVE_PERSIST_BIT(name, type, smask)                          \
    {                                                                                     \
        type _v_save_##name = (BITMAP_IS_SET(state->oms->oms_state_flags, tt::smask)      \
                                ? (type)1 : (type)0);                                     \
        if (fwrite(&_v_save_##name, sizeof(type), 1, f) != 1) goto fail;                  \
    }

#define OMS_PROJECT_PERSIST_SAVE_PERSIST_MULTI_BIT(name, type, smask)                    \
    static_assert(false,                                                                  \
                  "PERSIST + MULTI_BIT combination not yet implemented in OmsFieldRegistry.hpp. " \
                  "First user must design the wire format: save full int value via " \
                  "MBS_GET_U8 → fwrite; load → fread → MBS_SET_U8 commit. See header docs.");

#define OMS_PROJECT_PERSIST_SAVE_PERSIST_ATOMIC(name, type, smask)                       \
    static_assert(false,                                                                  \
                  "PERSIST + ATOMIC combination not yet implemented in OmsFieldRegistry.hpp. " \
                  "First user must design memory ordering: atomic_load at save; atomic_store at commit. " \
                  "See header docs.");

// ---- DECLARE (per-row tmp_<name> declarations at load site) ----
#define OMS_PROJECT_PERSIST_DECLARE(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_PERSIST_DECLARE_##pkind##_##skind(name, type)

#define OMS_PROJECT_PERSIST_DECLARE_SKIP_PERSIST_DIRECT(name, type)
#define OMS_PROJECT_PERSIST_DECLARE_SKIP_PERSIST_BIT(name, type)
#define OMS_PROJECT_PERSIST_DECLARE_SKIP_PERSIST_MULTI_BIT(name, type)
#define OMS_PROJECT_PERSIST_DECLARE_SKIP_PERSIST_ATOMIC(name, type)

#define OMS_PROJECT_PERSIST_DECLARE_PERSIST_DIRECT(name, type)    type tmp_##name = {};
#define OMS_PROJECT_PERSIST_DECLARE_PERSIST_BIT(name, type)       type tmp_##name = {};
#define OMS_PROJECT_PERSIST_DECLARE_PERSIST_MULTI_BIT(name, type) type tmp_##name = {};
#define OMS_PROJECT_PERSIST_DECLARE_PERSIST_ATOMIC(name, type)    type tmp_##name = {};

// ---- READ (fread into tmp_<name>) ----
#define OMS_PROJECT_PERSIST_READ(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_PERSIST_READ_##pkind##_##skind(name, type)

#define OMS_PROJECT_PERSIST_READ_SKIP_PERSIST_DIRECT(name, type)
#define OMS_PROJECT_PERSIST_READ_SKIP_PERSIST_BIT(name, type)
#define OMS_PROJECT_PERSIST_READ_SKIP_PERSIST_MULTI_BIT(name, type)
#define OMS_PROJECT_PERSIST_READ_SKIP_PERSIST_ATOMIC(name, type)

#define OMS_PROJECT_PERSIST_READ_PERSIST_DIRECT(name, type) \
    if (fread(&tmp_##name, sizeof(type), 1, f) != 1) { fclose(f); return 0; }
#define OMS_PROJECT_PERSIST_READ_PERSIST_BIT(name, type) \
    if (fread(&tmp_##name, sizeof(type), 1, f) != 1) { fclose(f); return 0; }
#define OMS_PROJECT_PERSIST_READ_PERSIST_MULTI_BIT(name, type) \
    if (fread(&tmp_##name, sizeof(type), 1, f) != 1) { fclose(f); return 0; }
#define OMS_PROJECT_PERSIST_READ_PERSIST_ATOMIC(name, type) \
    if (fread(&tmp_##name, sizeof(type), 1, f) != 1) { fclose(f); return 0; }

// ---- COMMIT (assign tmp_<name> back to OMS) ----
#define OMS_PROJECT_PERSIST_COMMIT(name, type, init, reset, rkind, skind, pkind, smask) \
    OMS_PROJECT_PERSIST_COMMIT_##pkind##_##skind(name, type, smask)

#define OMS_PROJECT_PERSIST_COMMIT_SKIP_PERSIST_DIRECT(name, type, smask)
#define OMS_PROJECT_PERSIST_COMMIT_SKIP_PERSIST_BIT(name, type, smask)
#define OMS_PROJECT_PERSIST_COMMIT_SKIP_PERSIST_MULTI_BIT(name, type, smask)
#define OMS_PROJECT_PERSIST_COMMIT_SKIP_PERSIST_ATOMIC(name, type, smask)

#define OMS_PROJECT_PERSIST_COMMIT_PERSIST_DIRECT(name, type, smask) \
    { state->oms->name = tmp_##name; }
#define OMS_PROJECT_PERSIST_COMMIT_PERSIST_BIT(name, type, smask)                         \
    {                                                                                      \
        if (tmp_##name) state->oms->oms_state_flags |=  (uint8_t)(tt::smask);              \
        else            state->oms->oms_state_flags &= (uint8_t)(~(uint8_t)(tt::smask));   \
    }
#define OMS_PROJECT_PERSIST_COMMIT_PERSIST_MULTI_BIT(name, type, smask)                   \
    static_assert(false,                                                                   \
                  "PERSIST + MULTI_BIT commit not yet implemented. "                        \
                  "First user: MBS_SET_U8(state->oms->oms_state_flags, smask, "             \
                  "__builtin_ctz(smask), tmp_##name).");
#define OMS_PROJECT_PERSIST_COMMIT_PERSIST_ATOMIC(name, type, smask)                      \
    static_assert(false,                                                                   \
                  "PERSIST + ATOMIC commit not yet implemented. "                           \
                  "First user: state->oms->name.store(tmp_##name, <documented order>).");

//------------------------------------------------------------------
// [SECTION]_[DISPATCH MACROS — PER_SLOT views]
//------------------------------------------------------------------
// Walked inside a for(_i=0..MAX_PORTFOLIO_POSITIONS) loop. Accessor includes
// [_i] so expansion produces `_oms->last_fill[_i].field = ...` etc.
#define OMS_PROJECT_PER_SLOT_INIT(accessor, type, init, reset) \
    _oms->accessor = (type)(init);
#define OMS_PROJECT_PER_SLOT_RESET(accessor, type, init, reset) \
    _oms->accessor = (type)(reset);

//======================================================================
// [FUNCTION]_[_oms_init_value_fields]
//----------------------------------------------------------------------
// [TAG]_[[ENGINE] [OMS_DRAINER] [BOOT_TIME]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[the registry-walk helper pair (_oms_reset_value_fields rides) — one instantiation per F; AUTOPOPULATE delegates the Layer-1 walk here (templated-helpers discipline; .B.7 precedent)]
//======================================================================
// [CODE]
//======================================================================
namespace tt {

template <unsigned F>
inline void _oms_init_value_fields(OrderManagerState<F>* _oms, const OmsInitCtx<F>& ctx) {
#define _OMS_INIT_ONE(NAME, TYPE, INIT, RESET, RKIND, SKIND, PKIND, SMASK) \
    OMS_PROJECT_INIT_##SKIND(NAME, TYPE, INIT, SMASK)
    FOREACH_OMS_FIELD(_OMS_INIT_ONE)
#undef _OMS_INIT_ONE
}

template <unsigned F>
inline void _oms_reset_value_fields(OrderManagerState<F>* _oms, const OmsResetCtx<F>& ctx) {
#define _OMS_RESET_ONE(NAME, TYPE, INIT, RESET, RKIND, SKIND, PKIND, SMASK) \
    OMS_PROJECT_RESET_##RKIND##_##SKIND(NAME, TYPE, RESET, SMASK)
    FOREACH_OMS_FIELD(_OMS_RESET_ONE)
#undef _OMS_RESET_ONE
}

}  // namespace tt
//======================================================================
// [END_CODE]
//======================================================================
// [COMMENT]
//----------------------------------------------------------------------
// Templated functions encapsulate the FOREACH walks; each is instantiated
// once per F (only F=64 today). AUTOPOPULATE macros delegate Layer 1 walk
// to these helpers; sub-struct inits (Portfolio_Init, per-slot loops, SPSC
// rings, event log) stay inline in the macro body (NOT walking the registry).
//======================================================================
// [END_FUNCTION]_[_oms_init_value_fields]
//======================================================================

//----------------------------------------------------------------------
// [MACRO]_[OMS_*_AUTOPOPULATE]
// [TAG]_[[ENGINE] [OMS_DRAINER] [BOOT_TIME] [FRAMEWORK_DISCIPLINE]]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[the one-line OMS call sites — INIT: 5 layers (registry walk / sub-structs+per-slot / SPSC rings / event-log load+replay / async writer LAST); RESET: RST walk + Portfolio_Init]
//----------------------------------------------------------------------
// OMS_INIT_AUTOPOPULATE(_oms, _adapter, _live_trading, _partial_exit_enabled,
//                        _starting_balance, _fee_rate, _event_log_mode, _event_log_path)
//   Boot-time full init of an OrderManagerState. Five layers:
//     Layer 1 — _oms_init_value_fields helper walks FOREACH_OMS_FIELD
//                (DIRECT + BIT + MULTI_BIT + ATOMIC rows all dispatched
//                 by STORAGE_KIND). Substrate row (oms_state_flags) runs
//                 first; BIT/MULTI_BIT rows then OR/AND their bits cleanly.
//     Layer 2 — Sub-struct inits: Portfolio_Init + per-slot Order_Init loop
//                (MAX_INFLIGHT_ORDERS) + per-slot FOREACH_OMS_PER_SLOT_FIELD
//                loop + OMS_META_CLEAR (MAX_PORTFOLIO_POSITIONS).
//     Layer 3 — SPSC ring inits (result + ws_result + reconcile +
//                MAX_EXECUTION_NODES submit queues).
//     Layer 4 — OrderEventLog conditional init + LoadFromDisk + replay.
//                MUST RUN BEFORE Layer 5 (StartAsyncWriter depends on
//                event_log being _Init-only or _InitWithFile'd).
//     Layer 5 — OrderEventLog_StartAsyncWriter (MUST RUN LAST).
//
// OMS_RESET_AUTOPOPULATE(_oms, _starting_balance)
//   Paper-reset of an OrderManagerState. Two layers:
//     Layer 1 — _oms_reset_value_fields helper walks FOREACH_OMS_FIELD
//                (RESET_KIND filters DO_RESET vs SKIP_RESET; SKIP_RESET
//                 rows emit no-op so their RESET expression never evaluated).
//     Layer 2 — Portfolio_Init (clears all positions).
//
// Why some sub-struct logic stays OUTSIDE the helper: helper-Init calls,
// per-slot loops, and SPSC ring inits aren't uniform per-row assignments —
// they're concern-specific calls that don't fit the registry's tuple shape.
//
// Pre-v5.15.5.C.3 design had 8 layers; this design collapses Layer 2
// (special-case scalars: adapter, oms_state_flags, event_log_mode) +
// Layer 3 (atomic stores: total_*, flatten_pending, recovery_until_us)
// into Layer 1 via STORAGE_KIND dispatch. Net: 8 → 5 layers, cleaner
// AUTOPOPULATE body, no more "where does this field live?" decision per
// future addition.

// AUTOPOPULATE macro parameter naming convention:
//   Parameter `_oms_target` distinguishes the caller's OMS pointer from the
//   INTERIOR variable `_oms` used by FOREACH_OMS_PER_SLOT_FIELD's
//   OMS_PROJECT_PER_SLOT_INIT macro (which hardcodes literal `_oms->accessor`).
//   Inside the per-slot loop block we declare `auto* _oms = _oms_target;`
//   so the per-slot macros find a literal `_oms` in scope. Same approach in
//   the templated helpers above — their function parameter is named `_oms`
//   so the OMS_PROJECT_INIT_*/RESET_* macros find it directly.

// v5.15.5.F.4c.3 WIP2d-1.B.1 — _fee_rate param DELETED from macro sig. Per-Order fee_rate
// lives on Order::pre_resolved (set at submit via Order_BindPreResolved); OMS-level scalar
// fee_rate fields deleted. Portfolio_FromEventLog passes FPN_Zero for event-log replay
// (replay can't reconstruct per-trade fees from price+qty alone; treated as recovery-path
// best-effort accounting, sister to Reconcile fallback semantic).
#define OMS_INIT_AUTOPOPULATE(_oms_target, _adapter, _live_trading, _partial_exit_enabled,          \
                              _starting_balance, _event_log_mode, _event_log_path)                   \
    do {                                                                                            \
        /* Build context struct from caller args; ctx is referenced by registry INIT expressions */ \
        tt::OmsInitCtx<F> _oms_init_ctx{                                                            \
            (_adapter),                                                                              \
            (_live_trading),                                                                         \
            (_partial_exit_enabled),                                                                 \
            (_event_log_mode),                                                                       \
            (_starting_balance),                                                                     \
            (_event_log_path)                                                                        \
        };                                                                                           \
        /* Layer 1 — registry-driven scalar/bit/multi-bit/atomic init via templated helper */       \
        tt::_oms_init_value_fields<F>((_oms_target), _oms_init_ctx);                                 \
        /* Layer 2 — sub-struct helper-Init + per-slot loops */                                     \
        Portfolio_Init(&(_oms_target)->portfolio);                                                   \
        for (int _i = 0; _i < MAX_INFLIGHT_ORDERS; ++_i) {                                           \
            Order_Init(&(_oms_target)->orders[_i], 0, -1, ORDER_MARKET_BUY);                         \
            Order_SetState(&(_oms_target)->orders[_i], ORDER_FILLED);                                \
        }                                                                                            \
        {                                                                                            \
            /* Declare literal-_oms local so OMS_PROJECT_PER_SLOT_INIT (hardcoded `_oms->accessor`) */ \
            /* finds it via the FOREACH_OMS_PER_SLOT_FIELD walk below.                              */ \
            auto* _oms = (_oms_target);                                                              \
            for (int _i = 0; _i < MAX_PORTFOLIO_POSITIONS; ++_i) {                                   \
                FOREACH_OMS_PER_SLOT_FIELD(OMS_PROJECT_PER_SLOT_INIT)                                \
                OMS_META_CLEAR(_oms->last_exit_predicted_meta[_i]);                                  \
            }                                                                                        \
        }                                                                                            \
        /* Layer 3 — SPSC ring inits */                                                              \
        SPSCRing_Init(&(_oms_target)->result_queue);                                                 \
        SPSCRing_Init(&(_oms_target)->ws_result_queue);                                              \
        SPSCRing_Init(&(_oms_target)->reconcile_queue);                                              \
        for (int _i = 0; _i < MAX_EXECUTION_NODES; ++_i) {                                           \
            SPSCRing_Init(&(_oms_target)->submit_queues[_i]);                                        \
        }                                                                                            \
        /* Layer 4 — OrderEventLog conditional init + LoadFromDisk + replay (MUST RUN BEFORE L5) */  \
        {                                                                                            \
            const char* _evt_path = (_event_log_path);                                                \
            int _has_disk_path = (_evt_path && _evt_path[0]);                                        \
            if ((_event_log_mode) == 1 && _has_disk_path) {                                          \
                OrderEventLog_Init(&(_oms_target)->event_log);                                       \
                int _loaded = OrderEventLog_LoadFromDisk(&(_oms_target)->event_log, _evt_path);      \
                if (_loaded > 0) {                                                                    \
                    /* v5.15.5.F.4c.3 WIP2d-1.B.1 — _fee_rate deleted; event-log replay can't */     \
                    /* reconstruct per-trade fees from price+qty (decision-time-data-binding-pattern.md */ \
                    /* recovery-path nullable semantic). Pass FPN_Zero — replayed balance reflects */     \
                    /* gross-of-fee P&L (acceptable for boot recovery; live HandleFill is authoritative). */ \
                    tt::FoldResult<F> _fold = Portfolio_FromEventLog(&(_oms_target)->event_log,      \
                                                                      (_starting_balance),           \
                                                                      Money_Zero());                 \
                    (_oms_target)->portfolio    = _fold.portfolio;                                   \
                    (_oms_target)->balance      = _fold.balance;                                     \
                    (_oms_target)->realized_pnl = _fold.realized_pnl;                                \
                    if (Money_Gt((_oms_target)->balance, (_oms_target)->ks_peak_balance))     \
                        (_oms_target)->ks_peak_balance = (_oms_target)->balance;                     \
                    std::fprintf(stderr, "[OMS] replayed %d events from disk, balance=$%.2f\n",      \
                                 _loaded, Money_ToDouble((_oms_target)->balance));                     \
                }                                                                                     \
                OrderEventLog_InitWithFile(&(_oms_target)->event_log, _evt_path);                    \
            } else {                                                                                  \
                OrderEventLog_Init(&(_oms_target)->event_log);                                       \
            }                                                                                        \
        }                                                                                            \
        /* Layer 5 — MUST RUN LAST: depends on event_log being _Init-only or _InitWithFile'd */     \
        OrderEventLog_StartAsyncWriter(&(_oms_target)->event_log);                                   \
    } while (0)

#define OMS_RESET_AUTOPOPULATE(_oms_target, _starting_balance)                                       \
    do {                                                                                             \
        /* Build reset context with starting_balance; ctx is referenced by DO_RESET rows */         \
        tt::OmsResetCtx<F> _oms_reset_ctx{ (_starting_balance) };                                    \
        /* Layer 1 — registry RESET walk; SKIP_RESET rows emit no-op (RESET expr never evaluated) */ \
        tt::_oms_reset_value_fields<F>((_oms_target), _oms_reset_ctx);                               \
        /* Layer 2 — Portfolio reset (clears all positions) */                                       \
        Portfolio_Init(&(_oms_target)->portfolio);                                                   \
    } while (0)

#endif  // OMS_FIELD_REGISTRY_HPP
